apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Self-contained deployment: includes own MinIO and Loki operator
resources:
- ../../base
- loki-operator.yaml
- minio.yaml
- s3-secret.yaml

patches:
- path: lokistack-patch.yaml
