apiVersion: v1
kind: Secret
metadata:
  name: loki-s3-secret
  namespace: netobserv
type: Opaque
stringData:
  endpoint: http://loki-minio.netobserv.svc.cluster.local:9000
  bucketnames: loki-data
  access_key_id: loki
  access_key_secret: lokisecret
