apiVersion: v1
kind: Secret
metadata:
  name: loki-s3-secret
  namespace: netobserv
type: Opaque
stringData:
  endpoint: http://minio.minio.svc.cluster.local:9000
  bucketnames: netobserv-loki
  access_key_id: minio
  access_key_secret: minio123
